name: Konnection library

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    #- name: Install gpg
    #  run: brew install gnupg

    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17

    #- name: Select Xcode
    #  run: sudo xcode-select -switch /Applications/Xcode_11.3.app

    - name: xcode version
      run: /usr/bin/xcodebuild -version

    - name: build library
      run: ./gradlew konnection:build

    - name: assemble xcFramework
      run: ./gradlew konnection-swift:assembleKonnectionReleaseXCFramework

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./

  sample-android:
    runs-on: macOS-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17

    - name: enter on artifact
      run: cd artifact

    - name: build sample app
      run: ./gradlew samples:android:build

  sample-ios:
    runs-on: macOS-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17

    #- name: Select Xcode
    #  run: sudo xcode-select -switch /Applications/Xcode_11.3.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: enter on artifact
      run: cd artifact

    - name: build sample app
      run: ./gradlew samples:ios:build

  sample-desktop:
    runs-on: macOS-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17

    - name: enter on artifact
      run: cd artifact

    - name: build sample app
      run: ./gradlew samples:desktop:build
