name: Sample Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17

    - name: build sample app
      run: ./gradlew samples:desktop:build
